
/**
 * Type representing a single running process
 *
 * @export
 * @type PsProcess
 */
export type PsProcess<C extends FormatSpecifierCode = FormatSpecifierCode> = {
    [index in C]: string;
};

export type FormatSpecifierCode =
    "%cpu" |
    "%mem" |
    "args" |
    "blocked" |
    "bsdstart" |
    "bsdtime" |
    "c" |
    "caught" |
    "cgname" |
    "cgroup" |
    "class" |
    "cls" |
    "cmd" |
    "comm" |
    "command" |
    "cp" |
    "cputime" |
    "drs" |
    "egid" |
    "egroup" |
    "eip" |
    "esp" |
    "etime" |
    "etimes" |
    "euid" |
    "euser" |
    "f" |
    "fgid" |
    "fgroup" |
    "flag" |
    "flags" |
    "fname" |
    "fuid" |
    "fuser" |
    "gid" |
    "group" |
    "ignored" |
    "ipcns" |
    "label" |
    "lstart" |
    "lsession" |
    "lwp" |
    "lxc" |
    "machine" |
    "maj_flt" |
    "min_flt" |
    "mntns" |
    "netns" |
    "ni" |
    "nice" |
    "nlwp" |
    "nwchan" |
    "ouid" |
    "pcpu" |
    "pending" |
    "pgrp" |
    "pid" |
    "pidns" |
    "pmem" |
    "policy" |
    "ppid" |
    "pri" |
    "psr" |
    "rgid" |
    "rgroup" |
    "rss" |
    "rssize" |
    "rsz" |
    "rtprio" |
    "ruid" |
    "ruser" |
    "s" |
    "sched" |
    "seat" |
    "sess" |
    "sgi_p" |
    "sgid" |
    "sgroup" |
    "sid" |
    "sig" |
    "sigcatch" |
    "sigignore" |
    "sigmask" |
    "size" |
    "slice" |
    "spid" |
    "stackp" |
    "start" |
    "start_time" |
    "stat" |
    "state" |
    "suid" |
    "supgid" |
    "supgrp" |
    "suser" |
    "svgid" |
    "svuid" |
    "sz" |
    "tgid" |
    "thcount" |
    "tid" |
    "time" |
    "tname" |
    "tpgid" |
    "trs" |
    "tt" |
    "tty" |
    "ucmd" |
    "ucomm" |
    "uid" |
    "uname" |
    "unit" |
    "user" |
    "userns" |
    "utsns" |
    "uunit" |
    "vsize" |
    "vsz" |
    "wchan";
